---
name: 'Terraform'

on:
  push:

permissions:
  id-token: write # for OIDC

jobs:
  plan:
    name: Terragrunt Plan
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: List files after checkout
        run: ls -lah

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Check caller identity
        run: aws sts get-caller-identity

      - name: Terragrunt init
        working-directory: ./terraform
        run: |
          cd terraform
          terragrunt init

      - name: Terragrunt plan
        run: |
          cd terraform
          terragrunt plan
